language: python

python:
  - "2.7"

before_install:
 - "sudo apt-get update"
 - "sudo apt-get install qemu"

install:
  - "pip install -r requirements.txt"

script:
 - "curl -O http://download.fedoraproject.org/pub/fedora/linux/updates/20/Images/x86_64/Fedora-x86_64-20-20140407-sda.qcow2"
 - "behave"
 - "rm -vf *.qcow2"
